# Generated by Django 5.1.8 on 2025-05-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idempotency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('rolled-back', 'Rolled Back')], default='applied', max_length=30)),
                ('path', models.CharField(max_length=500)),
                ('key', models.CharField(max_length=500)),
                ('request', models.JSONField()),
                ('response', models.JSONField()),
            ],
        ),
    ]
