# Generated by Django 5.1.8 on 2025-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_idempotency_request_alter_idempotency_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotency',
            name='help_data',
            field=models.JSONField(null=True),
        ),
    ]
