# Generated by Django 5.1.8 on 2025-05-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_idempotency_help_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotency',
            name='applied_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='idempotency',
            name='rolled_back_at',
            field=models.DateTimeField(null=True),
        ),
    ]
